export const timeStamps = [
    ['0:00:0', 'OUR GOD IS GOOD TO US<br><code>by Jaming</code>'],

    ['0:11:0', 'I know the Father covers me'],
    ['0:15:0', 'as the enemy surrounds'],
    ['0:18:0', 'My Shepard guards with rod and staff'],
    ['0:21:0', 'no sheep remain unfound'],
    ['0:25:0', 'The quiet waters I will find my,'],
    ['0:28:0', 'my fears have been relived'],
    ['0:32:0', 'And by my loving Saviour′s side'],
    ['0:35:0', 'forever I will be'],

    ['0:38:0', 'Our God is good to us'],
    ['0:45:0', '<b>Our God is good to us</b>'],
    ['0:51:0', 'Now we can stand on Christ our Rock'],
    ['0:54:0', 'and boldly we proclaim'],
    ['0:58:0', 'Our God is good to us'],
    ['1:05:0', '<b>Our God is good to us</b>'],

    ['01:14:0', 'I know the plans You have for me,'],
    ['01:17:0', 'are good and will fulfill'],
    ['01:21:0', 'The Work You have begun in me'],
    ['01:25:0', 'surrendered to Your will'],
    ['01:28:0', 'So send Your holy spirit lord,'],
    ['01:31:0', 'to guide my wondering heart'],
    ['01:34:0', 'My eyes forever fixed upon'],
    ['01:38:0', 'the promise of the Cross'],

    ['01:41:0', 'His hands and feet were pierced that day '],
    ['01:45:0', 'to save me from the grave'],
    ['01:48:0', 'The Father’s wrath for all my sin'],
    ['01:51:0', 'upon His head was laid'],
    ['01:54.5:0', 'And I who once, was bound by my sin'],
    ['01:58:0', 'by the Saviour′s blood set free.'],
    ['02:01:0', 'The Father’s gift of Saving grace'],
    ['02:04:0', 'was poured out over me'],

    ['02:07:0', 'Our God is good to us'],
    ['02:14:0', '<b>Our God is good to us</b>'],
    ['02:20:0', 'Now we can stand on Christ our Rock '],
    ['02:24:0', 'and boldly we proclaim'],
    ['02:27:0', 'Our God is good to us'],
    ['02:34:0', '<b>Our God is good to us</b>'],
    ['02:39:0', '...'],

    ['02:44:0', 'Our God is good to us'],
    ['02:51:0', '<b>Our God is good to us</b>'],
    ['02:57:0', 'Now we can stand on Christ our Rock '],
    ['03:1:0', 'and boldly we proclaim'],
    ['03:04:0', 'Our God is good to us'],
    ['03:10:0', '<b>Our God is good to us</b>'],
    ['03:15:0', '....'],

    ['03:20:0', 'When the Father calls us home '],
    ['03:23:0', 'His Word we long to hear'],
    ['03:27:0', '<q>My good and faithful children come,</q>'],
    ['03:29.5:0', '<q>and rest in Me draw near</q>'],
    ['03:34:0', 'And as we join in heavenly song,'],
    ['03:37:0', 'we offer grateful praise'],
    ['03:40:0', 'Unto the Lamb upon the throne'],
    ['03:44:0', 'the One who came to save.'],
    ['03:51:0', 'THANKS FOR WATCHING']
]